#!/usr/bin/env python3
"""
Step 6 — Figure 6: membrane MD pose stability + MM-GBSA binding-energy
ranking. Composites two figures generated by 04_make_figures.py (in this same
directory) into one two-panel figure.

Run 04_make_figures.py first so generated/figures/fig_md_rmsd_stability.png and
fig_mmgbsa_comparison.png exist (see the top-level README).

Run (from the repository root):
    python scripts/05_figures_and_statistics/08_render_figure6_md_stability.py

Output:
    generated/figures/Figure6_composite.png / .pdf / .tiff
"""
import os
from PIL import Image, ImageChops
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

FIGURES_DIR = "generated/figures"


def autocrop(img, padding=20):
    bg = Image.new(img.mode, img.size, (255, 255, 255))
    diff = ImageChops.difference(img.convert("RGB"), bg.convert("RGB"))
    bbox = diff.getbbox()
    if bbox:
        bbox = (max(0, bbox[0] - padding), max(0, bbox[1] - padding),
                min(img.width, bbox[2] + padding), min(img.height, bbox[3] + padding))
        return img.crop(bbox)
    return img


def main():
    img_a = autocrop(Image.open(os.path.join(FIGURES_DIR, "fig_md_rmsd_stability.png")))
    img_b = autocrop(Image.open(os.path.join(FIGURES_DIR, "fig_mmgbsa_comparison.png")))

    # Width ratios follow each cropped image's own aspect ratio (not a fixed
    # constant) so both panels render at the same height with width matching
    # their true content shape — a fixed ratio doesn't track either image's
    # actual aspect ratio, so imshow's aspect-preserving behaviour would
    # letterbox each panel independently and leave them visibly different sizes.
    aspect_a = img_a.width / img_a.height
    aspect_b = img_b.width / img_b.height

    fig = plt.figure(figsize=(14, 7), dpi=600)
    gs = gridspec.GridSpec(1, 2, figure=fig, width_ratios=[aspect_a, aspect_b], wspace=0.04)
    ax_a = fig.add_subplot(gs[0, 0])
    ax_b = fig.add_subplot(gs[0, 1])

    for ax, img, label in [(ax_a, img_a, "A"), (ax_b, img_b, "B")]:
        ax.imshow(img)
        ax.axis("off")
        ax.text(0.02, 0.98, label, transform=ax.transAxes,
                 fontsize=18, fontweight="bold", va="top", ha="left", color="black")

    os.makedirs(FIGURES_DIR, exist_ok=True)
    out_png = os.path.join(FIGURES_DIR, "Figure6_composite.png")
    out_pdf = os.path.join(FIGURES_DIR, "Figure6_composite.pdf")
    fig.savefig(out_png, dpi=600, bbox_inches="tight", facecolor="white")
    fig.savefig(out_pdf, bbox_inches="tight", facecolor="white")

    out_tiff = os.path.join(FIGURES_DIR, "Figure6_composite.tiff")
    Image.open(out_png).save(out_tiff, compression="tiff_lzw", dpi=(600, 600))
    print(f"wrote {out_png}, {out_pdf}, {out_tiff}")
    print(f"  aspect A={aspect_a:.3f}, aspect B={aspect_b:.3f}")


if __name__ == "__main__":
    main()
